### ISSUE TITLE
if a build output is required before publish, the latest PR build artifact is not used

### ISSUE THREAD

**Issue by NathanaelGandhi** [NathanaelGandhi/ng-template-repo#33]
- maybe check the latest artifacts for a matching tag and use that. else error?
- maybe only publish after PR
```
on:
  pull_request_target:
    types:
      - closed

jobs:
  publish:
    if: github.event.pull_request.merged == true
```
